add multi chain feature
ArcBlock/forge-cli pull request #126
Opened 2019-08-01 07:46 UTC by polunzh

- mainly includes:
  - create a new chain by `forge create-chain <chainName>`
  - enable start/stop/reset the specific chain by `forge <action> <chainName>| [--chain-chain <chainName>] | [-c <chainName>]`
  - `forge ps` will show all chains running processes
- remove `-m` param in `start` command
- refact the file management
- refact the forge process management
- deprecated use `forge-starter` to start the chain
- deprecated the `--force | -f` param of `forge stop` command, and add `--all | -a` to stop all chains

2019-08-01 23:35 UTC, wangshijun requested changes
great job!

2019-08-01 23:35 UTC, wangshijun commented on src/cli/node/install/index.js
> +  input => action(execute, run, input),
`install` 命令的 `init` 别名不要删除，不然有些老的脚本可能不工作了。

2019-08-01 23:35 UTC, wangshijun commented on src/cli/node/start/index.js
> +  'Start forge as a daemon in the background',
Update this description

2019-08-01 23:35 UTC, wangshijun commented on src/cli/node/start/index.js
> +      ['-m, --multiple', 'Allow start multiple forge node instances'],
Change log 里说这个删掉了？但是还没删？

2019-08-01 23:35 UTC, wangshijun commented on src/cli/node/start/start.js
> +async function main({ opts: { dryRun }, args: [chainName = process.env.PROFILE_NAME] }) {
所有跟 forge 有关的环境变量建议带上 `FORGE_` 前缀，这样便于隔离，也更容易推测

2019-08-01 23:35 UTC, wangshijun commented on src/cli/node/start/start.js
> +  if (await isForgeStarted(chainName)) {
这里既然知道了 chain name，应该在消息里面说清楚怎么停止这条链，forge stop 不带参数会不会引起混淆

2019-08-01 23:35 UTC, wangshijun commented on src/cli/node/stop/index.js
> +  - ${chalk.cyan('forge stop --all')}     same as above`);
输出没对齐吧

2019-08-01 23:35 UTC, wangshijun commented on src/cli/node/stop/stop.js
> +    let handle = null;
handle => handler

2019-08-01 23:35 UTC, wangshijun commented on src/cli/node/web/web.js
> -    debug(`${symbols.error} start webui failed: ${stderr}!`);
统一术语：`forge web start failed`

2019-08-01 23:35 UTC, wangshijun commented on src/cli/project/create/create.js
> +const { isFile, debug, webUrl } = require('core/env');
为什么 isDirectory 在 fs 模块里面，而 isFile 却没有？

2019-08-01 23:35 UTC, wangshijun commented on src/constant.js
> +  DEFAULT_CHAIN_NAME: 'default',
default 这个名字与没有更好的选项？

2019-08-01 23:35 UTC, wangshijun commented on src/core/forge-fs.js
> +  printWarning('Clearing data profiles');
text => Cleaning up chain data

2019-08-01 23:35 UTC, wangshijun commented on src/index.js
> +  printInfo(`run ${chalk.cyan('DEBUG=@arcblock/cli:* command')} to get details infomations`);
1. `command` 能不能具体点，毕竟这个时候我们知道用户跑的是啥命令了
2. get details information => get detail infomation

2019-08-06 01:37 UTC, polunzh commented
#11

2019-08-10 02:59 UTC, wangshijun approved these changes
lets ship it

2019-08-10 03:00 UTC, merged