no longer create a default chain before execute every command
ArcBlock/forge-cli pull request #254
Opened 2019-09-27 09:26 UTC by polunzh

2019-09-27 11:30 UTC, polunzh commented on src/cli/blocklet/use/index.js
> +    chainExists: false,
添加注释

2019-09-27 11:30 UTC, polunzh commented on src/cli/chain/create/index.js
> +    parseArgs: chainName => ({
注释

2019-09-27 11:30 UTC, polunzh commented on src/cli/node/install/install.js
> +    print(`Now you can create a forge node with ${chalk.cyan('forge chain:create')}`);
`Now you can create a chain...`

2019-09-27 11:30 UTC, polunzh commented on src/core/libs/common.js
> +const DEFAULT_CHAIN_NAME_RETURN = { no_chains: 1 };
大写

2019-09-27 11:30 UTC, polunzh commented on src/cli/node/stop/index.js
> +      chainName: async ({ chainName }) => {
可以用`requirement.currentChainRunning`

2019-09-27 11:30 UTC, polunzh commented on src/cli/node/stop/index.js
> +    parseArgs: chainName => chainName,
bug: chainName => ({chainName})

2019-09-27 11:30 UTC, polunzh commented on src/cli/node/stop/stop.js
> +  const allProcesses = await getAllRunningProcesses();
可以删除

2019-09-27 11:30 UTC, polunzh commented on src/cli/release/use/index.js
> +  - ${chalk.cyan('forge use 0.38.0')}      activate forge v0.38.0
可以读 engines.forge
还有 install/index.js

2019-09-27 11:30 UTC, polunzh commented on src/core/env.js
> + * TODO: args 参数应该可以去掉
args 参数应该可以去掉

2019-09-27 11:30 UTC, polunzh commented on src/core/env.js
> +async function ensureRunningNode(requirement) {
runningChain

2019-09-27 11:30 UTC, polunzh commented on src/core/env.js
> +  const chainNames = getAllChainNames();
common有封装的方法。

2019-09-27 11:30 UTC, polunzh commented on src/core/env.js
> +    process.env.FORGE_CURRENT_CHAIN = chainNames[0][0]; // eslint-disable-line
再封装一次getAllChainNames

2019-09-27 11:30 UTC, polunzh commented on src/core/env.js
> +    printInfo(`Please run ${chalk.cyan(`forge start ${chainName}`)} first!`);
warnning时process退出码为0

2019-09-27 11:30 UTC, polunzh commented on src/core/env.js
> +    printError(`forge-cli requires a valid forge config file to start
直接throw 没有有效的配置

2019-09-27 11:30 UTC, polunzh commented on src/cli/node/config/lib.js
> +  const chainId = strEqual(name, DEFAULT_CHAIN_NAME) ? 'forge' : name;
删除 DEFAULT_CHAIN_NAME

2019-09-29 03:30 UTC, polunzh commented on src/cli/node/stop/index.js
> +      chainName: async ({ chainName }) => {
这个地方不能用 `requirement.currentChainRunning` 替代，因为这个地方是取当前启动的链，而不是看当前链是不是启动。

2019-09-29 22:18 UTC, wangshijun commented
Bug:

```
❯ ls ~/.forge_chains
ls: /Users/wangshijun/.forge_chains: No such file or directory
```

```
❯ forge chain:create wangshijun -d
✔ Initialized an empty storage space in /Users/wangshijun/.forge_chains/forge_default
✔ Extract forge config from /Users/wangshijun/.forge_cli/release/forge/0.38.2/lib/forge-0.38.2/priv/forge_release.toml
✔ Forge config written to /Users/wangshijun/.forge_chains/forge_default/forge_release.toml
✔ chain name: wangshijun
✖ Create new chain failed:
✖ Cannot read property 'address' of undefined
```

2019-09-29 22:26 UTC, wangshijun commented
@polunzh please run test with a clean setup (empty .forge_cli and empty .forge_chains)

- `forge install`
- `forge chain:create xxx -d`
- `forge start`
- `forge stop`

As I have tested, the second step is not robust due to following reasons:

- the chain:create will crash if `FORGE_MODERATOR_SK` not set in env
- Got wrong moderator and `accounts` when `FORGE_MODERATOR_SK` not set in env

2019-09-29 22:57 UTC, wangshijun requested changes
I have some comments in the pr, please resolve them before publish

2019-09-29 22:57 UTC, wangshijun commented on src/cli/chain/list/list.js
> +    printInfo(`There is no chains, you can create by run ${chalk.cyan('forge chain:create')}`);
there are no chains, you can create one by ...

2019-09-30 03:41 UTC, polunzh commented
> @polunzh please run test with a clean setup (empty .forge_cli and empty .forge_chains)
> 
> * `forge install`
> * `forge chain:create xxx -d`
> * `forge start`
> * `forge status`
> * `forge stop`
> * `forge download`
> * `forge upgrade`
> 
> As I have tested, the second step is not robust due to following reasons:
> 
> * the chain:create will crash if `FORGE_MODERATOR_SK` not set in env
> * neither `forge config set` nor `forge chain:create` prints the randomly generated token holder wallet on complete.
> 
> ## duplicate chain creating issue
> cli fails without any error message or error log when I create a chain with name that has already been created.
> 
> ```
> forge chain:create wangshijun -d
> forge chain:create wangshijun -d
> ```
> 
> ## `wallet:*` should not require a chain
> ```
> ❯ forge wallet:create --defaults
> ⚠ There are no chains, please create it by run forge chain:create
> ```
> 
> But `account:*` requires a chain
> 
> ## web port for first chain should be 8210?
> Only 1 chain was ever created on my test machine, but the web port is not 8210, I strongly suggest we keep things consistent, because 8210 is a widely known port for our developer users.

Resolved:
1. fixed duplicate chain creating issue
1. `wallet:create` command is no longer need a chain
1. `account:*` commands need an existed chain
1.  first chain's default web port will be 8210
1. if the chain used the generated token holder, cli will print the holder's sk/pk/address

2019-09-30 06:12 UTC, wangshijun approved these changes

2019-09-30 06:12 UTC, merged

2019-10-08 01:20 UTC, polunzh commented
Relate issue:
https://github.com/ArcBlock/forge-cli/issues/240