fix: moderator is required by forge #291
ArcBlock/forge-cli pull request #295
Opened 2019-10-20 09:34 UTC by polunzh

2019-10-24 10:14 UTC, wangshijun requested changes

2019-10-24 10:14 UTC, wangshijun commented on src/cli/node/config/lib.js
> +  if (generatedModeratorSK) {
既然用户没有设置 moderator sk，并且我们给他生成了 sk，那么干脆放到全局的配置文件里面好了。这个提示里面说明下把什么信息写到了配置文件里面即可。

这样做了之后，用户甚至不需要学习什么是 moderator sk，就能很流畅的使用 upgrade、deploy 等命令。而对于链节点的运维人员，我们会有文档专门说明这个事情，就是在他们需要的时候有资料能知道。

2019-10-24 10:14 UTC, wangshijun commented on src/cli/node/config/lib.js
> +  if (generatedModeratorSK) {
另外，我测试的时候模拟无 moderator sk 设置的情形，结果 “Moderator sk was not set in local environment” 输出了两次，这个请优化下。

2019-10-24 10:28 UTC, polunzh commented on src/cli/node/config/lib.js
> +  if (generatedModeratorSK) {
> 既然用户没有设置 moderator sk，并且我们给他生成了 sk，那么干脆放到全局的配置文件里面好了。这个提示里面说明下把什么信息写到了配置文件里面即可。
> 
> 这样做了之后，用户甚至不需要学习什么是 moderator sk，就能很流畅的使用 upgrade、deploy 等命令。而对于链节点的运维人员，我们会有文档专门说明这个事情，就是在他们需要的时候有资料能知道。

全局配置文件指的是 `~/.forgerc.yml`?

2019-10-25 07:36 UTC, polunzh commented on src/cli/node/config/lib.js
> +  if (generatedModeratorSK) {
Added.

2019-10-25 07:37 UTC, polunzh commented
Preserve generated sk to global config file:

![image](https://user-images.githubusercontent.com/4244426/67552246-4093bb00-f73d-11e9-9093-ff89e5cb2166.png)

2019-10-25 08:50 UTC, merged